blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/', views.accueil, name='accueil'),
    path('/articles', views.articles_list, name='articles_list'),
    path('article/create', views.contact_create, name='contact_create'),
    path('article/<article-id>', views.contact_detail, name='contact_detail'),
]

monsite/contact/urls.py
from django.urls import path
from . import views
# Afficher les contacts
# Afficher la fiche du contact
# Créer un contact
# Modifier un contact
# Supprimer les contacts

app_name = 'contact'

urlpatterns = [
    path('', views.contact_list, name='contact_list'),
    path('person/<int:id>', views.contact_detail, name='contact_detail'),
    path('person/new', views.contact_new, name='contact_new'),
    path('person/<int:id>/edit', views.contact_edit, name='contact_edit'),
    path('person/<int:id>/delete', views.contact_delete, name='contact_delete'),
]

monsite/monsite/urls.py
from django.contrib import admin
from django.urls import include, path

from . import settings
from . import views
from django.conf.urls.static import static

# Liste permettant de définir les routes de notre application
urlpatterns = [
    # path prend en paramètres (obligatoires) la route et la vue associée
    # path("admin/", admin.site.urls),
    path("toto", views.toto, name="toto"),
    # Il est possible de capturer les paramètres dans nos URLs avec les chevrons
    path('articles/<int:annee>/<slug:mois>', views.article_annee_mois, name="article"),
    path('contact/', include('contact.urls')),
]

# On ajoute les fichiers statiques aux URLs
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/monsite/models.py
from django.db import models

# Create your models here.

monsite/contact/models.py
from django.db import models

# Create your models here.

monsite/contact/models/config.py
configdb = {
    'host': 'localhost',
    'username':'root',
    'password':'',
    'database':'annuaire'
}

monsite/contact/models/contact.py
from datetime import date
from .config import configdb
import mysql.connector

class Contact:

    # Constructeur
    def __init__(self, id, firstname, lastname, birth_date, phone, email): 
        self.id = id
        self.firstname = firstname
        self.lastname = lastname
        self.birth_date = birth_date
        self.phone = phone
        self.email = email

    # Permet de retourner l'age comme un attribut de l'objet
    @property
    def full_name(self): 
        return f'{self.firstname[:1].upper()}{self.firstname[1:].lower()} {self.lastname.upper()}'

    # La soustraction est un booléen qui retourne 0 ou 1 selon l'age de la personne
    @property
    def age(self):
        today = date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        return age
        
    def __str__(self): 
        return f"""
        id : {self.id}
        identité : {self.full_name}
        age : {self.age}
        telephone : {self.phone}
        email : {self.email}
        """
    @staticmethod
    def get_all_contacts():

        contacts = []

        with mysql.connector.connect(**configdb) as db: 
            with db.cursor() as cursor:
                query = "SELECT contact_id, firstname, lastname, birth_date, phone, email FROM contact"
                try:
                    cursor.execute(query)
                    results = cursor.fetchall()

                    # Parcours du jeu de résultats pour créer des contacts et les ajouter dans un tableau
                    for id, firstname, lastname, birth_date, phone, email in results:
                        contact = Contact(id, firstname, lastname, birth_date, phone, email)
                        contacts.append(contact)
                
                except Exception as ex:
                    print(ex)
        return contacts

blog/monsite/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect

from .models.contact import Contact

from .forms import ContactForm


def accueil(request):
    return pass

def article_list(request):
    return pass

def contact_create(request):
    return pass

def contact_detail(request):
    return pass

monsite/contact/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models.contact import Contact

# Retourne la liste des contacts
def contact_list(request):
    contacts = Contact.get_all_contacts()
    print(len(contacts))
    return render(request, 'contact/contact-list.html')

def contact_detail(request):
    return HttpResponse("Liste des contacts")

def contact_new(request):
    return HttpResponse("Liste des contacts")

def contact_edit(request):
    return HttpResponse("Liste des contacts")

def contact_delete(request):
    return HttpResponse("Liste des contacts")

monsite/monsite/views.py
from django.http import HttpResponse

# Les vues prennent une requête http en entrée et retourne une requête http
def toto(request):
    return HttpResponse("Toto")

# Les paramètres captés dans les urls doivent être précisés dans la vue
def article_annee_mois(request, annee, mois):
    return HttpResponse(f"{annee} {mois}")

monsite/contact/templates/base.html
{# On charge les fichiers statics #}

{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# on fait référence à notre fichier css #}
    <link rel="stylesheet" href="{% static 'contact/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'contact:contact_list' %}">Accueil</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact_new' %}">Créer un contact</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </header>

    <main>
        <div class="container">
            {% block content %}
            {# injection d'autres élément html #}
            {% endblock %}
          </div>
        <!-- {# on fait référence à notre image jpg #}
        <img src="{% static 'contact/img/xp.jpg' %}" alt="wallpaper windows xp"> -->
    </main>
</body>
</html>

monsite/contact/templates/contact/contact-list.html
{% extends 'base.html' %}

{% block title %}Liste de contacts{% endblock %}

{% block content %}

<p>Je suis une liste de contacts</p>

{% endblock %}

monsite/contact/templates/contact/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toto</title>
</head>
<body>
    <p>bonjour {{ first_name }} {{ last_name }}</p>
</body>
</html>